version: "3"
services:
  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-kw
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - ./src/test/resources/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
