version: '3.1'
services:
  new-nomis-ui:
    image: mojdigitalstudio/new-nomis-ui:latest
    depends_on:
      - oauth-server
      - elite2-api
      - keyworker-api
    container_name: new-nomis-ui
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
      - PORT=3000
      - OAUTH_ENDPOINT_URL=http://oauth-server:8080/auth/
      - API_ENDPOINT_URL=http://elite2-api:8080/
      - KEYWORKER_API_URL=http://keyworker-api:8080/
      - OMIC_UI_URL=http://localhost:3001/
      - ESTABLISHMENT_ROLLCHECK_URL=http://localhost:3002/establishmentroll
      - WHEREABOUTS_UI_URL=http://localhost:3002/whereaboutssearch

  omic-ui:
    image: mojdigitalstudio/omic-ui:latest
    depends_on:
      - oauth-server
      - elite2-api
      - keyworker-api
    container_name: omic-ui
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
      - PORT=3000
      - OAUTH_ENDPOINT_URL=http://oauth-server:8080/auth/
      - API_ENDPOINT_URL=http://elite2-api:8080/
      - KEYWORKER_API_URL=http://keyworker-api:8080/
      - NN_ENDPOINT_URL = http://localhost:3000/
      - MAINTAIN_ROLES_ENABLED=true

  prisonstaffhub:
    image: mojdigitalstudio/whereabouts:latest
    depends_on:
      - oauth-server
      - elite2-api
    container_name: prisonstaffhub
    ports:
      - "3002:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    environment:
      - PORT=3000
      - OAUTH_ENDPOINT_URL=http://oauth-server:8080/auth/
      - API_ENDPOINT_URL=http://elite2-api:8080/
      - NN_ENDPOINT_URL = http://localhost:3000/

  oauth-server:
    image: mojdigitalstudio/nomis-oauth2-server:latest
    container_name: oauth-server
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  elite2-api:
    image: mojdigitalstudio/elite2-api:latest
    container_name: elite2-api
    depends_on:
      - oauth-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  keyworker-api:
    image: mojdigitalstudio/keyworker-api:latest
    depends_on:
      - elite2-api
      - oauth-server
    container_name: keyworker-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - ELITE2_URI_ROOT=http://elite2-api:8080
      - AUTH_URI_ROOT=http://oauth-server:8080/auth
      - security.require-ssl=false
