hmpps.sqs:
  provider: localstack
  queues:
    offenderevents:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: keyworkerevents
    complexityofneed:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: complexityevents
  topics:
    keyworkerevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    complexityevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
