hmpps.sqs:
  provider: localstack
  queues:
    offenderevents:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: keyworkerevents
    domaineventsqueue:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: domaineventstopic
  topics:
    keyworkerevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    domaineventstopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
