apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-keyworker-recon
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: recon-keyworker-api
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPOST http://keyworker-api/batch/key-worker-recon
          restartPolicy: Never
