apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  ELITE2API_CLIENT_CLIENTID: {{ .Values.secrets.ELITE2API_CLIENT_CLIENTID | b64enc | quote }}
  ELITE2API_CLIENT_CLIENTSECRET: {{ .Values.secrets.ELITE2API_CLIENT_CLIENTSECRET | b64enc | quote }}
