apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-update-status
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "25 9-13 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron-job-name: updatestatus-cronjob
        spec:
          containers:
            - name: updatestatus-keyworker-api
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPOST http://keyworker-api/batch/update-status
          restartPolicy: Never
