---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: dps-db-snapshot-job
  name: dps-prometheus-rules-db-snapshot
spec:
  groups:
  - name: kubernetes-apps
    rules:
    - alert: DB-rds-snapshot-job-failed
      annotations:
        message: Database snapshot job {{ $labels.namespace }}/{{ $labels.job_name }} failed to complete.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubejobfailed
      expr: max(kube_job_status_failed{namespace="keyworker-api-dev",job_name=~"rds-snapshot-job.*"}) by (namespace, pod, job_name) > 0
      for: 1m
      labels:
        severity: digital-prison-service

