# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:

 env:
  SENTRY_ENVIRONMENT: dev
  PRISON_URI_ROOT: "https://prison-api-dev.prison.service.justice.gov.uk"
  MANAGE_USERS_API_URI_ROOT: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
  CASE_NOTES_API_URI_ROOT: "https://dev.offender-case-notes.service.justice.gov.uk"
  PRISONER_SEARCH_API_URI_ROOT: "https://prisoner-search-dev.prison.service.justice.gov.uk"
  PRISON_REGISTER_API_URI_ROOT: "https://prison-register-dev.hmpps.service.justice.gov.uk"
  AUTH_URI_ROOT: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  COMPLEXITY_OF_NEED_URI: "https://complexity-of-need-staging.hmpps.service.justice.gov.uk"
  NOMIS_USER_ROLES_API_URI_ROOT: "https://nomis-user-roles-api-dev.prison.service.justice.gov.uk"

 ingress:
   host: keyworker-api-dev.prison.service.justice.gov.uk

 allowlist: false

generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod
  rdsAlertsDatabases:
    cloud-platform-a75ed0cca96e6c72: 'Keyworker API'
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-keyworker-dev-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-keyworker-dev-keyworker_domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  businessHoursOnly: true
  applicationCronJobStatusFailedWindowMinutes: 10

schedule:
 prison_stats: "0 7 * * *"