generic-service:

  env:
    SENTRY_ENVIRONMENT: prod
    PRISON_URI_ROOT: "https://prison-api.prison.service.justice.gov.uk"
    MANAGE_USERS_API_URI_ROOT: "https://manage-users-api.hmpps.service.justice.gov.uk"
    CASE_NOTES_API_URI_ROOT: "https://offender-case-notes.service.justice.gov.uk"
    PRISONER_SEARCH_API_URI_ROOT: "https://prisoner-search.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URI_ROOT: "https://prison-register.hmpps.service.justice.gov.uk"
    AUTH_URI_ROOT: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    COMPLEXITY_OF_NEED_URI: https://complexity-of-need.hmpps.service.justice.gov.uk
    NOMIS_USER_ROLES_API_URI_ROOT: "https://nomis-user-roles-api.prison.service.justice.gov.uk"
    KEYWORKER_ENABLED_FOR_PRISONS: ""

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

  ingress:
    host: keyworker-api.prison.service.justice.gov.uk

  allowlist:
    groups:
      - internal

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-prod
  rdsAlertsDatabases:
    cloud-platform-fa888e83362e61b1: "Keyworker API"
  rdsAlertsConnectionThreshold: 100
  sqsOldestAlertQueueNames:
    - "hmpps-keyworker-prod-domain_events_queue"
  sqsAlertsOldestThreshold: 10
  sqsNumberAlertQueueNames:
    - "hmpps-keyworker-prod-keyworker_domain_events_dlq"
  sqsAlertsTotalMessagesThreshold: 1
  applicationCronJobStatusFailedWindowMinutes: 15

schedule:
  prison_stats: "5 0 * * *"