# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:

 env:
  PRISON_URI_ROOT: "https://prison-api-dev.prison.service.justice.gov.uk"
  AUTH_URI_ROOT: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
  COMPLEXITY_OF_NEED_URI: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
  PRISONS_WITH_OFFENDERS_THAT_HAVE_COMPLEX_NEEDS: "LEI,MDI,AGI,BZI,DHI,DWI,ESI,EWI,FHI,LNI,NHI,PFI,SDI,STI"

 ingress:
   host: keyworker-api-dev.prison.service.justice.gov.uk

 allowlist: false

generic-prometheus-alerts:
 alertSeverity: hmpps-alerts-api-non-prod
 rdsAlertsDatabases:
  cloud-platform-a75ed0cca96e6c72: 'Keyworker API'