# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/keyworker-api
  tag: latest
  port: 8080

ingress:
  enabled: true
  enable_whitelist: false
  hosts:
    - host: keyworker-api-dev.prison.service.justice.gov.uk
      cert_secret: keyworker-api-cert
  path: /

env:
  ELITE2_URI_ROOT: "https://api-dev.prison.service.justice.gov.uk"
  AUTH_URI_ROOT: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
  JAVA_OPTS: "-Xmx512m"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
  WOMENS_ESTATE: "MDI,LEI"
  COMPLEXITY_OF_NEED_API_URI: "https://hmpps-complexity-of-need-staging.apps.live-1.cloud-platform.service.justice.gov.uk"