DROP TABLE IF EXISTS KEYWORKER_STATS;

CREATE TABLE KEYWORKER_STATS
(
  KEYWORKER_STATS_ID        BIGSERIAL    NOT NULL,
  PRISON_ID                 VARCHAR( 6)  NOT NULL,
  SNAPSHOT_DATE             TIMESTAMP    NOT NULL,
  NUM_PRISONERS_ASSIGNED_KW  INTEGER      NOT NULL,
  TOTAL_NUM_PRISONERS       INTEGER      NOT NULL,
  NUM_KW_SESSIONS           INTEGER,
  NUM_KW_ENTRIES            INTEGER,
  NUM_ACTIVE_KEYWORKERS     INTEGER,
  RECPT_TO_ALLOC_DAYS       INTEGER,
  RECPT_TO_KW_SESSION_DAYS  INTEGER,

  CONSTRAINT KEYWORKER_STATS_PK PRIMARY KEY (KEYWORKER_STATS_ID)
);

COMMENT ON TABLE KEYWORKER_STATS IS 'Records the results of each statistic snapshot';

COMMENT ON COLUMN KEYWORKER_STATS.KEYWORKER_STATS_ID      IS 'Primary key ID';
COMMENT ON COLUMN KEYWORKER_STATS.PRISON_ID               IS 'Prison ID';
COMMENT ON COLUMN KEYWORKER_STATS.SNAPSHOT_DATE           IS 'Timestamp of date for which stats apply';

COMMENT ON COLUMN KEYWORKER_STATS.NUM_PRISONERS_ASSIGNED_KW  IS 'Number of prisoner who have been assigned a Key worker';
COMMENT ON COLUMN KEYWORKER_STATS.TOTAL_NUM_PRISONERS       IS 'Total number of prisoners in the prison on this date';
COMMENT ON COLUMN KEYWORKER_STATS.NUM_KW_SESSIONS           IS 'Number of Key worker case note sessions';
COMMENT ON COLUMN KEYWORKER_STATS.NUM_KW_ENTRIES            IS 'Number of Key worker case note entries';
COMMENT ON COLUMN KEYWORKER_STATS.NUM_ACTIVE_KEYWORKERS     IS 'Number of active keyworkers';
COMMENT ON COLUMN KEYWORKER_STATS.RECPT_TO_ALLOC_DAYS       IS 'Number of days (avg) between reception and allocation of a keyworker';
COMMENT ON COLUMN KEYWORKER_STATS.RECPT_TO_KW_SESSION_DAYS  IS 'Number of days (avg) between reception and first Key worker session';

INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-14','700','805','0','12','116','3','54');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-15','700','805','0','4','118','2','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-16','702','802','0','0','117','4','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-17','704','815','500','0','134','5','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-18','720','814','0','13','130','4','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-19','710','799','30','15','125','3','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-20','711','800','10','12','127','2','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-21','711','802','10','8','127','4','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-22','740','803','10','8','127','6','54');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-23','740','804','10','8','127','34','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-24','734','810','10','8','127','3','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-25','735','801','10','8','127','5','7');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-26','712','803','10','8','127','3','7');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-27','732','805','10','8','127','2','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-28','700','805','8','12','120','23','8');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-29','702','805','5','4','121','4','43');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-30','702','802','6','0','117','4','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-08-31','704','815','7','0','134','6','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-01','720','814','0','13','130','3','7');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-02','710','799','11','15','125','3','78');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-03','711','800','13','12','127','23','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-04','711','802','10','8','127','5','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-05','740','803','10','8','127','6','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-06','740','804','10','8','127','43','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-07','734','810','10','8','127','32','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-08','735','801','10','8','127','23','7');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-09','712','803','10','8','127','3','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-10','732','805','10','8','127','4','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-11','700','805','8','12','120','5','7');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-12','702','805','5','4','121','3','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-13','702','802','6','0','117','6','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-14','704','815','7','0','134','7','2');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-15','720','814','0','13','130','5','2');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-16','710','799','11','15','125','6','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-17','711','800','13','12','127','4','2');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-18','711','802','10','8','127','3','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-19','740','803','10','8','127','2','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-20','740','804','10','8','127','2','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-21','734','810','10','8','127','4','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-22','735','801','10','8','127','5','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-23','712','803','10','8','127','5','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-24','732','805','10','8','127','6','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-25','700','805','8','12','120','3','56');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-26','702','805','5','4','121','4','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-27','702','802','6','0','117','23','7');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-28','704','815','7','0','134','2','6');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-29','720','814','0','13','130','3','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-09-30','710','799','11','15','125','6','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-01','711','800','13','12','127','6','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-02','711','802','10','8','127','6','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-03','740','803','10','8','127','5','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-04','740','804','10','8','127','7','2');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-05','734','810','10','8','127','3','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-06','735','801','10','8','127','6','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-07','712','803','10','8','127','3','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-08','732','805','10','8','127','67','4');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-09','704','805','8','12','120','7','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-10','720','802','5','4','121','8','5');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-11','710','815','6','0','117','3','3');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-12','711','814','7','0','134','2','2');
INSERT INTO KEYWORKER_STATS (PRISON_ID, SNAPSHOT_DATE, NUM_PRISONERS_ASSIGNED_KW, TOTAL_NUM_PRISONERS, NUM_KW_SESSIONS, NUM_KW_ENTRIES, NUM_ACTIVE_KEYWORKERS, RECPT_TO_ALLOC_DAYS, RECPT_TO_KW_SESSION_DAYS) VALUES ('MDI','2018-10-13','720','799','0','13','130','2','4');