ALTER TABLE KEYWORKER_STATS ADD COLUMN TOTAL_NUM_ELIGIBLE_PRISONERS INTEGER;
UPDATE KEYWORKER_STATS SET TOTAL_NUM_ELIGIBLE_PRISONERS = TOTAL_NUM_PRISONERS;
ALTER TABLE KEYWORKER_STATS ALTER COLUMN TOTAL_NUM_ELIGIBLE_PRISONERS SET NOT NULL;
