ALTER TABLE PRISON_SUPPORTED ADD KW_SESSION_FREQ_WEEKS INT;

UPDATE PRISON_SUPPORTED SET KW_SESSION_FREQ_WEEKS = 1;

ALTER TABLE PRISON_SUPPORTED ALTER COLUMN KW_SESSION_FREQ_WEEKS SET NOT NULL;

COMMENT ON COLUMN PRISON_SUPPORTED.KW_SESSION_FREQ_WEEKS IS 'Key worker session frequency for the prison';
