CREATE INDEX OFFENDER_KEY_WORKER_ON_IDX ON OFFENDER_KEY_WORKER (OFFENDER_NO);
CREATE INDEX OFFENDER_KEY_WORKER_SI_IDX ON OFFENDER_KEY_WORKER (STAFF_ID);
CREATE INDEX OFFENDER_KEY_WORKER_AI_IDX ON OFFENDER_KEY_WORKER (AGY_LOC_ID);

