ALTER TABLE PRISON_SUPPORTED ADD CAPACITY_TIER_1 INT;
ALTER TABLE PRISON_SUPPORTED ADD CAPACITY_TIER_2 INT;

UPDATE PRISON_SUPPORTED SET CAPACITY_TIER_1 = 6, CAPACITY_TIER_2 = 9;

ALTER TABLE PRISON_SUPPORTED ALTER COLUMN CAPACITY_TIER_1 SET NOT NULL;

COMMENT ON COLUMN PRISON_SUPPORTED.CAPACITY_TIER_1 IS 'Default capacity for keyworkers at this prison';
COMMENT ON COLUMN PRISON_SUPPORTED.CAPACITY_TIER_2 IS 'Default extended capacity for keyworkers at this prison';
