# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: keyworker-api

generic-service:
  nameOverride: keyworker-api
  serviceAccountName: keyworker-api
  productId: DPS023

  image:
    repository: quay.io/hmpps/keyworker-api
    tag: latest
    port: 8080

  env:
    JDK_JAVA_OPTIONS: "-Xmx512m -XX:+UseG1GC"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "sqs"
    SERVER_CONNECTION_TIMEOUT: "180000"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException,org.springframework.web.servlet.resource.NoResourceFoundException,org.springframework.web.context.request.async.AsyncRequestNotUsableException"

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 1024Mi
    limits:
      cpu: 2048m
      memory: 1280Mi

  ingress:
    enabled: true
    host: app-hostname.local
    tlsSecretName: keyworker-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        location /batch/key-worker-recon {
          deny all;
          return 401;
        }
        location /batch/update-status {
          deny all;
          return 401;
        }
        location /prison-statistics/calculate {
          deny all;
          return 401;
        }

  namespace_secrets:
    keyworker-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      CLIENT_ID: CLIENT_ID
      CLIENT_SECRET: CLIENT_SECRET
      SENTRY_DSN: SENTRY_DSN
      SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    dps-rds-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DB_NAME: "database_name"
      DB_ENDPOINT: "rds_instance_endpoint"
    kw-sqs-instance-output:
      HMPPS_SQS_QUEUES_OFFENDEREVENTS_QUEUE_NAME: "sqs_kw_name"
    kw-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_OFFENDEREVENTS_DLQ_NAME: "sqs_kw_name"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
    domain-events-queue-secret:
      HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_QUEUE_NAME: "queue_name"
    domain-events-dlq-secret:
      HMPPS_SQS_QUEUES_DOMAINEVENTSQUEUE_DLQ_NAME: "queue_name"

  allowlist:
    groups:
      - internal

  retryDlqCronjob:
    enabled: true
    retryDlqSchedule: "0/30 * * * *"
