# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: keyworker-api

generic-service:
  nameOverride: keyworker-api
  serviceAccountName: keyworker-api
  productId: DPS023

  image:
    repository: quay.io/hmpps/keyworker-api
    tag: latest
    port: 8080

  env:
    JDK_JAVA_OPTIONS: "-Xmx512m -XX:+UseG1GC"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "sqs"
    SERVER_CONNECTION_TIMEOUT: "180000"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 1024Mi
    limits:
      cpu: 2048m
      memory: 1280Mi

  ingress:
    enabled: true
    host: app-hostname.local
    tlsSecretName: keyworker-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        location /batch/key-worker-recon {
          deny all;
          return 401;
        }
        location /batch/generate-stats {
          deny all;
          return 401;
        }
        location /batch/update-status {
          deny all;
          return 401;
        }

  namespace_secrets:
    keyworker-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      PRISONAPI_CLIENT_CLIENTID: "PRISONAPI_CLIENT_CLIENTID"
      PRISONAPI_CLIENT_CLIENTSECRET: "PRISONAPI_CLIENT_CLIENTSECRET"
    dps-rds-instance-output:
      SPRING_DATASOURCE_USERNAME: "database_username"
      SPRING_DATASOURCE_PASSWORD: "database_password"
      DB_NAME: "database_name"
      DB_ENDPOINT: "rds_instance_endpoint"
    kw-sqs-instance-output:
      HMPPS_SQS_QUEUES_OFFENDEREVENTS_QUEUE_NAME: "sqs_kw_name"
    kw-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_OFFENDEREVENTS_DLQ_NAME: "sqs_kw_name"
    kw-sqs-complexity-of-need-instance-output:
      HMPPS_SQS_QUEUES_COMPLEXITYOFNEED_QUEUE_NAME: "sqs_kw_name"
    kw-sqs-complexity-of-need-dl-instance-output:
      HMPPS_SQS_QUEUES_COMPLEXITYOFNEED_DLQ_NAME: "sqs_kw_name"

  allowlist:
    groups:
      - internal
